---
title: "Histogram"
author: "Kyle Rodriguez"
date: "1/17/2022"
output: html_document
---

## Histograms  

```{r}
library(dplyr)
library(tidyverse)
library(plotly)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(data.table)
library(scales)
library(plotly)
```

```{r}
Lend <- fread('C:/Users/rodri/Desktop/NCFS2/DataVis/Datasets/LendingClubLoanData.csv')
Lend
```

```{r}
lend2 <- Lend %>% select(int_rate)%>%count(int_rate)
lend2
summary(lend2)
```

```{r}
# div10 <- trans_new(name ='div10',transform = function(x)x/10^4)
width <- 2
p1 <-ggplot(data = Lend,aes(x=int_rate))+
  geom_histogram(aes(y=stat(count)/10000),
                 color='black',
                 fill='lightblue',
                 center=15,
                 binwidth = width,
                 closed="left") +
  geom_density(aes(y=width*stat(count)/10000),
               size=.8,
               adjust=4,
               color='red')+
  theme_classic()+
  labs(x='Interest Rate',
       y = 'Number of Loans \nin Ten Thousands',
       title = 'Interest Rates of Loans',
       subtitle = 'Given by Lending Club'
       )+
  scale_y_continuous(expand=c(0,0))+
  scale_x_continuous(breaks = seq(0,35,5))+
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)
        )

p2 <- ggplot(data = Lend, aes(x=int_rate)) +
  geom_boxplot(fill="lightblue", outlier.shape=21,
               outlier.fill="lightblue",
               outlier.alpha=0.3) + theme_classic() +
  theme(
    axis.line.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.title.x=element_blank(),
    axis.line.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank(),
    axis.title.y=element_blank()
    )
hist_box <- plot_grid(p1,p2,ncol = 1, rel_heights = c(0.85, 0.15), align = 'v', axis = 'lr')
hist_box
save_plot('hist_boxplot.png',hist_box)
```


```{r}
GSS2018 <- read.csv('C:/Users/rodri/Desktop/NCFS2/DataVis/Datasets/GSS2018.csv')

```

```{r}
 GSS2018.pray1 <- GSS2018 %>% mutate(across(everything(),as.character)) %>% select(pray,relig)%>% mutate(relig1=fct_lump(relig,n=4)) %>% group_by(pray) %>% count(relig1,sort = TRUE) %>% drop_na()%>% mutate(Percent=100*(n/sum(n))) 

GSS2018.pray1
    
```
